OD-15942 - Jetty upgrade up to 10.0.6
ishgroup/oncourse pull request #423
Opened 2021-08-23 08:39 UTC by KeyrisXdSnow

2021-08-23 13:18 UTC, ArtyomKravchenko approved these changes

2021-08-23 13:19 UTC, ArtyomKravchenko commented
All is correct now

2021-09-01 09:54 UTC, ari commented
Why aren't we going to Jetty 11?

2021-09-03 08:07 UTC, ari requested changes
There are still test failures here, so no point in reviewing yet.

2021-09-03 12:25 UTC, ArtyomKravchenko approved these changes

2021-09-09 07:34 UTC, closed without merging