OD-16387 New columns for all list views
ishgroup/oncourse pull request #429
Opened 2021-08-24 12:52 UTC by dmitars

…ith bad performance

2021-08-25 06:23 UTC, ArtyomKravchenko requested changes

2021-08-25 06:23 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/cayenne/CourseClass.groovy
> +		return startDateTime == null || startDateTime.after(new Date());
let's check startDateTime != null && startDateTime.after(new Date());
If class has no startDateTime - it is unscheduled or distant learning

2021-08-25 06:23 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/cayenne/MembershipProduct.groovy
> +	Long getActiveMembershipsCount() {
What the purpose to keep interface in cayenne but implementation in trait, just move that methods it trait complitely

2021-08-25 06:23 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/cayenne/MembershipProduct.groovy
> +	Long getSoldCount() {
same problem

2021-08-25 06:23 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/cayenne/Outcome.groovy
> +		return enrolment != null ? getPresentAttendancePercent() : 0
Move in trait please

2021-08-25 06:23 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/cayenne/OutcomeTrait.groovy
> +        return Math.round(getAttendedAttendancesDuration().doubleValue() / getMaxPossibleAttendedDuration().doubleValue() * 100)
What if the divider is 0 here?

2021-08-25 06:23 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/cayenne/OutcomeTrait.groovy
> +    BigDecimal getNotMarkedAttendancesDuration() {
I'd like you to write the unit test for all OutcomeTrait methods please

2021-08-25 06:23 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/cayenne/RoomTrait.groovy
> +        def classes = getCourseClasses()
That is dangerous method invocation (potentially a lots of classes can be here), replace with select count please

2021-08-25 06:23 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/cayenne/RoomTrait.groovy
> +        def classes = getCourseClasses()
Same problemm

2021-08-25 06:24 UTC, ArtyomKravchenko approved these changes

2021-08-25 07:44 UTC, ArtyomKravchenko requested changes

2021-08-25 07:44 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/preference/DefaultUserPreference.groovy
> +                new ColumnDTO(title: 'Credit points', attribute: Module.CREDIT_POINTS.name, sortable: true, width: W100, visible: false, type: ColumnTypeDTO.MONEY),
Money is wrong here

2021-08-25 07:44 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/preference/DefaultUserPreference.groovy
> +                new ColumnDTO(title: 'Future classes', attribute: Site.FUTURE_CLASSES_COUNT_KEY, sortable: false, width: W200, visible: false),
Room prefetch here

2021-08-25 07:44 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/preference/DefaultUserPreference.groovy
> +                new ColumnDTO(title: 'Paid total', attribute: Payslip.PAID_TOTAL_KEY, sortable: false, width: W100, visible: false),
Prefetch payslip here

2021-08-25 07:44 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/preference/DefaultUserPreference.groovy
> +                new ColumnDTO(title: 'Data collection',
Add fieldConfigurationScheme prefetch

2021-08-25 07:44 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/preference/DefaultUserPreference.groovy
> +                new ColumnDTO(title: 'Grading type', attribute: Assessment.GRADING_TYPE.dot(GradingType.TYPE_NAME).name, sortable: false, width: W200, visible: false),
GradingType prefetch

2021-08-25 07:44 UTC, ArtyomKravchenko commented on server/src/main/groovy/ish/oncourse/server/preference/DefaultUserPreference.groovy
> +                new ColumnDTO(title: 'Assessor', attribute: AssessmentSubmission.MARKED_BY.dot(Contact.FULL_NAME_KEY).name, sortable: false, width: W200, visible: false),
Prefetch here

2021-08-25 13:28 UTC, ArtyomKravchenko approved these changes

2021-08-25 13:33 UTC, ArtyomKravchenko approved these changes

2021-08-27 11:08 UTC, ArtyomKravchenko submitted a review, later dismissed

2021-09-09 22:04 UTC, GFilipovich approved these changes

2021-09-09 22:04 UTC, merged