Script query expression using hours and minutes showing as invalid OD-16537
ishgroup/oncourse pull request #527
Opened 2021-11-08 06:47 UTC by KeyrisXdSnow

2021-11-15 23:00 UTC, ari commented
@KeyrisXdSnow You need to add some tests to this PR.

2021-11-15 23:00 UTC, ari requested changes
Tests required.

2021-11-19 09:47 UTC, KeyrisXdSnow commented
> Tests required.
All right, 
I added tests in last commit.

2022-02-02 04:47 UTC, GFilipovich submitted a review, later dismissed

2022-02-04 08:44 UTC, yuryyas approved these changes

2022-02-06 22:50 UTC, ari approved these changes

2022-02-06 23:38 UTC, merged