Change default notification templates OD-16539
ishgroup/oncourse pull request #528
Opened 2021-11-08 13:01 UTC by KeyrisXdSnow

2021-11-09 22:12 UTC, ari requested changes

2021-11-09 22:12 UTC, ari commented on server/src/main/resources/scripts/ish.script.sendTutorClassCommencementNotice.groovy
> +        query "isCancelled is false and startDateTime not is null and startDateTime after today + 1 days and startDateTime before today + ${number_of_days} days"
Surely this isn't correct?

2021-11-10 06:27 UTC, KeyrisXdSnow commented on server/src/main/resources/scripts/ish.script.sendTutorClassCommencementNotice.groovy
> +        query "isCancelled is false and startDateTime not is null and startDateTime after today + 1 days and startDateTime before today + ${number_of_days} days"
> Surely this isn't correct?

The original expression is correct, but in task it was necessary to replace constant value of days with the one setted via the UI

2021-11-10 08:32 UTC, ari commented on server/src/main/resources/scripts/ish.script.sendTutorClassCommencementNotice.groovy
> +        query "isCancelled is false and startDateTime not is null and startDateTime after today + 1 days and startDateTime before today + ${number_of_days} days"
There is no way your expression is correct. You want to send this out every day?

2021-11-11 07:40 UTC, KeyrisXdSnow commented on server/src/main/resources/scripts/ish.script.sendTutorClassCommencementNotice.groovy
> +        query "isCancelled is false and startDateTime not is null and startDateTime after today + 1 days and startDateTime before today + ${number_of_days} days"
Then, if I understood you correctly, the original query was wrong. Let's take a look at an example so that I understand my mistake:

Let's say the scheduler runs a task every day at 8 am. Only in case of a successful query will the messages be sent.

Our request template:
query "isCancelled is false and startDateTime not is null and startDateTime after today + 1 days and startDateTime before today + ${number_of_days} days".

Let's say we set option 'number_of_days' to 3, then after parsing the query will look like this:
query "isCancelled is false and startDateTime not is null and startDateTime after today + 1 days and startDateTime before today + 3 days".
Then the original request is obtained.

2021-11-12 21:57 UTC, ari commented on server/src/main/resources/scripts/ish.script.sendTutorClassCommencementNotice.groovy
> +        query "isCancelled is false and startDateTime not is null and startDateTime after today + 1 days and startDateTime before today + ${number_of_days} days"
This script should send the message only once, x days before the class starts.

2021-12-06 10:42 UTC, KeyrisXdSnow commented on server/src/main/resources/scripts/ish.script.sendTutorClassCommencementNotice.groovy
> +        query "isCancelled is false and startDateTime not is null and startDateTime after today + 1 days and startDateTime before today + ${number_of_days} days"
I change and simplify query

2021-12-10 03:03 UTC, ari requested changes

2021-12-10 03:03 UTC, ari commented on server/src/main/resources/scripts/ish.script.sendTutorClassCommencementNotice.groovy
> +        query "isCancelled is false and startDateTime not is null and startDateTime after today + 1 days and startDateTime before today + ${number_of_days} days"
This is still wrong. @yuryyas Could you please explain this to @KeyrisXdSnow

2021-12-15 11:17 UTC, GFilipovich approved these changes

2021-12-24 12:47 UTC, GFilipovich approved these changes

2021-12-28 10:52 UTC, ari approved these changes

2021-12-28 10:58 UTC, merged