Od 14963 put unreplicated message person to replication queue on server starts
ishgroup/oncourse pull request #540
Opened 2021-11-16 11:49 UTC by dmitars

2021-11-19 10:57 UTC, ari requested changes

2021-11-22 23:23 UTC, ari requested changes

2021-11-22 23:23 UTC, ari commented on server/src/main/resources/database/106.upgrade.yml
> +                        WHERE mp.emailFrom IS NULL'
Perhaps a better WHERE is

 WHERE mp.emailSubject IS NULL and mp.smsText IS NULL

2021-12-03 09:59 UTC, GFilipovich approved these changes

2021-12-03 15:53 UTC, GFilipovich approved these changes

2021-12-03 15:53 UTC, GFilipovich approved these changes

2021-12-03 16:10 UTC, yuryyas approved these changes

2021-12-03 16:10 UTC, yuryyas approved these changes

2021-12-03 16:15 UTC, yuryyas approved these changes

2021-12-03 16:17 UTC, closed without merging