CourseClass bulk edit view: renamed forward and backward to later and earlier
ishgroup/oncourse pull request #544
Opened 2021-11-17 12:12 UTC by chintankotadia

2021-11-19 10:51 UTC, ari commented
@chintankotadia Can we have JEST tests in here?

2021-11-29 13:59 UTC, yuryyas requested changes

2021-12-01 16:02 UTC, yuryyas approved these changes

2021-12-08 14:42 UTC, GFilipovich approved these changes

2021-12-13 09:10 UTC, yuryyas commented
Moved to epic branch

2021-12-13 09:10 UTC, closed without merging