OD-16686 Client tests library issues
ishgroup/oncourse pull request #607
Opened 2022-01-04 06:25 UTC by chintankotadia

2022-01-12 12:32 UTC, yuryyas requested changes

2022-01-12 12:32 UTC, yuryyas commented on client-html/src/js/common/components/form/Uneditable.tsx
> +  const inputId = `input-${label.toLowerCase().replace(' ', '-')}`;
@chintankotadia, what if we don't specify label?

2022-01-12 12:32 UTC, yuryyas commented on client-html/src/js/common/components/layout/expandable/ExpandableContainer.tsx
> +            data-testid={`expand-button-${index}`}
@chintankotadia , why do we need all this test-ids in production? Could we include them only in test environment?

2022-01-12 12:32 UTC, yuryyas commented on client-html/src/js/containers/entities/courseClasses/components/timetable/CourseClassBulkChangeSession.tsx
> +export const COURSE_CLASS_BULK_UPDATE_FORM: string = "CourseClassBulkUpdateForm";
@chintankotadia , Do not place exported constants inside components. We have constants folder for this. if constant is not used anywhere else, id does not need to be exported

2022-01-12 12:32 UTC, yuryyas commented on client-html/src/js/containers/entities/courseClasses/components/timetable/CourseClassBulkChangeSession.tsx
> -                        hideArrows
@chintankotadia Why you removed hideArrows?

2022-01-12 12:32 UTC, yuryyas commented on client-html/package.json
> +    "@testing-library/user-event": "^13.5.0",
@chintankotadia all this should be in dev dependencies. We don't use test libraries in production

2022-01-13 12:29 UTC, chintankotadia commented on client-html/src/js/common/components/form/Uneditable.tsx
> +  const inputId = `input-${label.toLowerCase().replace(' ', '-')}`;
Then we can't get input value, for uneditable field we don't specify/pass name, so must have to check it using label text, please check it out: https://testing-library.com/docs/queries/bylabeltext/

2022-01-13 12:31 UTC, chintankotadia commented on client-html/src/js/common/components/layout/expandable/ExpandableContainer.tsx
> +            data-testid={`expand-button-${index}`}
Specify for trigger click event, it can't break anything in production mode, please check it out: https://testing-library.com/docs/queries/bytestid, for these type of props we have to add condition of environment, but data-testid prop shows blank value.

2022-01-13 12:31 UTC, chintankotadia commented on client-html/src/js/containers/entities/courseClasses/components/timetable/CourseClassBulkChangeSession.tsx
> +export const COURSE_CLASS_BULK_UPDATE_FORM: string = "CourseClassBulkUpdateForm";
These type of constant is component itself not a global, it just a form name used in jest test also, so we don't bother when we change form name.

2022-01-13 12:32 UTC, chintankotadia commented on client-html/src/js/containers/entities/courseClasses/components/timetable/CourseClassBulkChangeSession.tsx
> -                        hideArrows
You had removed that props, made these changes in your commit, please check it out: https://github.com/ishgroup/oncourse/commit/ab035486f2c2d2edf9857c8eeb87f64b0d0cb992#diff-eb016cbc66e88ecd753374f5687db1e8dec4e1401a25754de63c81e37625de6bL577

2022-01-13 12:33 UTC, chintankotadia commented on client-html/package.json
> +    "@testing-library/user-event": "^13.5.0",
Moved to devDependecies

2022-01-13 13:24 UTC, yuryyas commented on client-html/src/js/common/components/form/Uneditable.tsx
> +  const inputId = `input-${label.toLowerCase().replace(' ', '-')}`;
You does't understand the issue. Label is not required property. What if we will use component without it? It will brake the code for did't add check that it exists

2022-01-13 13:29 UTC, yuryyas commented on client-html/src/js/common/components/layout/expandable/ExpandableContainer.tsx
> +            data-testid={`expand-button-${index}`}
The fact that it doesn't break anything doesn't mean that we need redundant ids in production. Don't we have the way to check if it tests running render or production code? And to not add this to DOM in production ?

2022-01-18 07:07 UTC, chintankotadia commented on client-html/src/js/common/components/layout/expandable/ExpandableContainer.tsx
> +            data-testid={`expand-button-${index}`}
Prevented data-testid to render in development/production mode, it only render in jest test env.

2022-01-18 07:22 UTC, chintankotadia commented on client-html/src/js/common/components/form/Uneditable.tsx
> +  const inputId = `input-${label.toLowerCase().replace(' ', '-')}`;
All the jest test created by us manually, so we have to careful about these, if label not specified. For these type of situation we can use other method of testing-library.

2022-01-20 09:29 UTC, yuryyas commented on client-html/src/js/common/components/form/Uneditable.tsx
> +  const inputId = `input-${label.toLowerCase().replace(' ', '-')}`;
@chintankotadia Just add check if label exists or make required

2022-01-20 09:59 UTC, chintankotadia commented on client-html/src/js/common/components/form/Uneditable.tsx
> +  const inputId = `input-${label.toLowerCase().replace(' ', '-')}`;
Made label prop required.

2022-01-24 07:12 UTC, yuryyas approved these changes

2022-01-25 15:17 UTC, yuryyas approved these changes

2022-01-26 09:50 UTC, closed without merging